name: real_debrid
description: A telegram bot to interact with real debrid API.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  intl: ^0.20.2
  path: ^1.9.0
  televerse: ^3.0.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
